# Generated by Django 5.2.8 on 2025-11-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('image', models.ImageField(upload_to='uploads/coatings/')),
            ],
            options={
                'verbose_name': 'Polewa',
                'verbose_name_plural': 'Polewy',
            },
        ),
        migrations.CreateModel(
            name='Sprinkle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('image', models.ImageField(upload_to='uploads/sprinkles/')),
            ],
            options={
                'verbose_name': 'Posypka',
                'verbose_name_plural': 'Posypki',
            },
        ),
        migrations.CreateModel(
            name='Donut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('image', models.ImageField(upload_to='uploads/donuts/')),
                ('is_custom_base', models.BooleanField(default=False)),
                ('coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coating')),
                ('sprinkle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sprinkle')),
            ],
            options={
                'verbose_name_plural': 'Donuty',
            },
        ),
    ]
