# Generated by Django 5.2.8 on 2025-12-09 16:45

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('image', models.ImageField(upload_to='uploads/top_coatings/')),
            ],
            options={
                'verbose_name': 'Dodatkowa Polewa',
                'verbose_name_plural': 'Dodatkowe Polewy',
            },
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', shop.models.CustomUserManager()),
            ],
        ),
    ]
