# Generated by Django 5.2.8 on 2025-12-17 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_topcoating_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='top_coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.topcoating'),
        ),
    ]
