# Generated by Django 5.2.8 on 2026-01-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_donut_top_coating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coating',
            name='image',
            field=models.ImageField(upload_to='uploads/coatings/', verbose_name='obraz'),
        ),
        migrations.AlterField(
            model_name='coating',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='coating',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='donut',
            name='coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coating', verbose_name='polewa'),
        ),
        migrations.AlterField(
            model_name='donut',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='donut',
            name='image',
            field=models.ImageField(upload_to='uploads/donuts/', verbose_name='obraz'),
        ),
        migrations.AlterField(
            model_name='donut',
            name='is_custom_base',
            field=models.BooleanField(default=False, verbose_name='baza do kreatora'),
        ),
        migrations.AlterField(
            model_name='donut',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='donut',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='donut',
            name='sprinkle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sprinkle', verbose_name='posypka'),
        ),
        migrations.AlterField(
            model_name='donut',
            name='top_coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.topcoating', verbose_name='dodatkowa polewa'),
        ),
        migrations.AlterField(
            model_name='sprinkle',
            name='image',
            field=models.ImageField(upload_to='uploads/sprinkles/', verbose_name='obraz'),
        ),
        migrations.AlterField(
            model_name='sprinkle',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='sprinkle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='topcoating',
            name='image',
            field=models.ImageField(upload_to='uploads/top_coatings/', verbose_name='obraz'),
        ),
        migrations.AlterField(
            model_name='topcoating',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='topcoating',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='cena'),
        ),
    ]
